# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rack-php-session}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Adam Daniels"]
  s.date = %q{2010-04-13}
  s.description = %q{Exposes a PHP Session (read-only) to Rack applications}
  s.email = %q{adam@mediadrive.ca}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "example/config.ru",
     "lib/rack-php-session.rb",
     "lib/rack/php-session.rb",
     "test/fixtures/sess_b6c1556e31e663f35b042c8b8369b75e",
     "test/helper.rb",
     "test/test_rack-php-session.rb"
  ]
  s.homepage = %q{http://github.com/adam12/rack-php-session}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Read-only access to PHP Sessions from Rack Applications}
  s.test_files = [
    "test/helper.rb",
     "test/test_rack-php-session.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<php-serialize>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<php-serialize>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<php-serialize>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

